server:
  port: 8081
  name: hh

spring:
  application:
    name: zuul-gateway

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

zuul:
  ignoredServices: '*'
  servletPath: /api/
  routes:
    apps:
      path: /apps/**
      serviceId: springcloud-apps

apps:
  ribbon:
    listOfServers: 127.0.0.1:8080,localhost:8080

ribbon:
  eureka:
    enabled: false